baseurl = "http://hoxo-m.com/blog"
title = "株式会社ホクソエムのブログ"
theme = "ghostwriter"
languageCode = "ja-JP"
copyright = "HOXOM, Inc."
googleAnalytics = "UA-87778111-3"
hasCJKLanguage = true

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "ホクソエムブログ"
    description = "株式会社ホクソエムのブログ"
    github = "https://github.com/HOXOMInc"
#    gitlab = "https://gitlab.com/XXX"
#    linkedin = "https://linkedin.com/in/XXX/"
#    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/hoxom_inc"
#    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
#    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
