baseurl         = "https://yutannihilation.github.io/HOXOMinc-blog/"
title           = "株式会社ホクソエムのブログ"
theme           = "ghostwriter"
languageCode    = "ja-JP"
copyright       = "HOXOM, Inc."
googleAnalytics = "XXXXXXXXXXX"
hasCJKLanguage  = true
publishDir      = "docs"
rssLimit        = 10
enableEmoji     = true

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "ホクソエムブログ"
    description = "株式会社ホクソエムのブログ"
    github = "https://github.com/HOXOMInc"
    twitter = "https://twitter.com/hoxom_inc"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
