---
title: "「東京ベイエリア・タワーマンション地図」の作成"
author: "Shinichi Takayanagi"
date: 2017-05-07T21:00:00-09:00
tags: ["R"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
options(warn = -1)
```

## はじめに
キュッキュキュッキュ🎧こんばんはDJタカヤナギです😤。

今日で連休が終わるという方が大半なのではないでしょうか？
長い連休明けの月曜日はいつだって嫌なものですね。

さて、東京オリンピックまであと3年ということで、その中心地となるであろう東京湾周辺、通称、東京ベイエリアが熱いわけです。
特にここ数年で高騰したタワーマンション（以下、タワマン）や、
これからもガンガン建設されていく予定のまだ見ぬタワマンに対し、投資対象として強い興味があるわけです。

主に、弊社の社長が。 

ただ、東京ベイエリアのタワマンと言いましても数がたくさんありすぎて覚えられないぞと、
一目で、どれがどのタワマンかわかるような地図が必要だぞというわけで、それをR言語を用いて作ってみましたので、その方法を公開します。

## R言語での実装

さて、問題となるのはタワマン一覧のデータソースですが、ここでは[アクセルホームさん](http://www.axel-home.com/)が公開されている

- http://www.axel-home.com/towers/chuo/index.html
- http://www.axel-home.com/towers/koto/index.html

あたりをソースとさせていただきました（実際には当該ページから次のページへと遷移した数ページも使用）。
こちら、よくまとまっており、大変助かります。
なお、中央区(chuo)・江東区(koto)ともに3ページ分のデータが存在することについては目視確認です。

なお、スマホ用のページが存在することに後から気が付いたのですが、今回はPC用のサイトでそのままがんばりました。
スマホ用のページの方が、一般に構造が簡単なので、スクレイピングするにはお勧めです。

これらのページから、必要な情報を取得するためのスクレイピング関数を作成します。
詳細はコード中のコメントとして記載しています。
コードはすべて

- [こちらのGist](https://gist.github.com/shinichi-takayanagi/c4830e46563e3dd9a9a1c2e1328e0eac)

にあります。

どこのHTMLタグのどのデータを抜けば良いのかの"当たり"を付けるためにはGoogle Chromeの「検証ツール」を用いました。

関数自体はやっつけで書いたので、汚いです…

## 東京ベイエリア・タワーマンション地図
出来上がった結果がこちらです。ベイエリアと言いながら街中まで入ってしまっているのを除くのは読者への課題とします。

また、[こちら](/post/tokyo-bay-area-tower-map_files/map.html)に飛べば全画面にて表示されます。

Enjoy!!!

<iframe src="/post/tokyo-bay-area-tower-map_files/map.html" name="in" width="800" height="600">


